#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-FreezeThaw
Version  : 0.5001
Release  : 20
URL      : https://cpan.metacpan.org/authors/id/I/IL/ILYAZ/modules/FreezeThaw-0.5001.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/I/IL/ILYAZ/modules/FreezeThaw-0.5001.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libf/libfreezethaw-perl/libfreezethaw-perl_0.5001-2.debian.tar.xz
Summary  : ~
Group    : Development/Tools
License  : Artistic-1.0 GPL-1.0
Requires: perl-FreezeThaw-license = %{version}-%{release}
Requires: perl-FreezeThaw-perl = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
This program is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

%package dev
Summary: dev components for the perl-FreezeThaw package.
Group: Development
Provides: perl-FreezeThaw-devel = %{version}-%{release}
Requires: perl-FreezeThaw = %{version}-%{release}

%description dev
dev components for the perl-FreezeThaw package.


%package license
Summary: license components for the perl-FreezeThaw package.
Group: Default

%description license
license components for the perl-FreezeThaw package.


%package perl
Summary: perl components for the perl-FreezeThaw package.
Group: Default
Requires: perl-FreezeThaw = %{version}-%{release}

%description perl
perl components for the perl-FreezeThaw package.


%prep
%setup -q -n FreezeThaw-0.5001
cd %{_builddir}
tar xf %{_sourcedir}/libfreezethaw-perl_0.5001-2.debian.tar.xz
cd %{_builddir}/FreezeThaw-0.5001
mkdir -p deblicense/
cp -r %{_builddir}/debian/* %{_builddir}/FreezeThaw-0.5001/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-FreezeThaw
cp %{_builddir}/debian/copyright %{buildroot}/usr/share/package-licenses/perl-FreezeThaw/9b762f1c99b2ef4648cc70f29b95b950521a90e5
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/FreezeThaw.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-FreezeThaw/9b762f1c99b2ef4648cc70f29b95b950521a90e5

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
