#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-FreezeThaw
Version  : 1
Release  : 6
URL      : https://cpan.metacpan.org/authors/id/I/IL/ILYAZ/modules/etext/etext.1.6.3.zip
Source0  : https://cpan.metacpan.org/authors/id/I/IL/ILYAZ/modules/etext/etext.1.6.3.zip
Source1  : http://http.debian.net/debian/pool/main/libf/libfreezethaw-perl/libfreezethaw-perl_0.5001-2.debian.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Artistic-1.0 GPL-1.0
BuildRequires : buildreq-cpan

%description
Etext is a drop in replacement for the Tk text widget. Currently there
are two differences (if we forget about bugs):  addition of another
type of text annotation: a block, and addition of an "object-oriented
dump" command.

%prep
%setup -q -n etext
cd ..
%setup -q -T -D -n etext -b 1
mkdir -p deblicense/
cp -r %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/etext/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-FreezeThaw
cp deblicense/copyright %{buildroot}/usr/share/package-licenses/perl-FreezeThaw/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
